version: '3'

services:
###> doctrine/doctrine-bundle ###
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
      - "3179:3179"
    depends_on:
      - database
    networks:
      - cards
    extra_hosts:
      - "cards.local:127.0.0.1"


  redis:
    image: redislabs/redisearch:latest
    ports:
      - "6379:6379"
    networks:
      - cards

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cards_against_x
      MYSQL_USER: cards_against_x
      MYSQL_PASSWORD: cards_against_x
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - cards

  pma:
    image: phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: database
    ports:
      - "8080:80"
    networks:
      - cards
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
#  mercure:
#    image: dunglas/mercure
#    restart: unless-stopped
#    environment:
#      SERVER_NAME: ':80'
#      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
#      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
#      MERCURE_EXTRA_DIRECTIVES: |
#        cors_origins http://cards.local
#    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
#    volumes:
#      - mercure_data:/data
#      - mercure_config:/config
#    networks:
#      - cards
###< symfony/mercure-bundle ###

networks:
  cards:
    driver: bridge