# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.host: '%env(APP_HOST)%'

    app.locales:
        - en
        - hu

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Security/FormLogin/FormLoginAuthenticator.php'

    App\Security\FormLogin\FormLoginAuthenticator:
        autowire: false
        arguments:
            $failureHandler: '@App\Security\FormLogin\Handlers\FailureHandler'
            $successHandler: '@App\Security\FormLogin\Handlers\SuccessHandler'
            $httpUtils: '@security.http_utils'
            $urlGenerator: '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
            $userProvider: '@security.user.provider.concrete.app_user_provider'
            $httpKernel: '@http_kernel'
            $options:
                check_path: login
                login_path: login
                username_parameter: 'login[email]'
                password_parameter: 'login[password]'
                use_forward: false

    App\Processor\Game\TurnStatusProcessor:
        autowire: true
        tags:
            - { name: 'app.game_processor', priority: 10 }

    App\Processor\Game\RoundProcessor:
        autowire: true
        tags:
            - { name: 'app.game_processor', priority: 20 }

    App\Processor\Game\CurrentRoundProcessor:
        autowire: true
        tags:
            - { name: 'app.game_processor', priority: 30 }

    App\Processor\Game\GameStatusProcessor:
        autowire: true
        tags:
            - { name: 'app.game_processor', priority: 40 }

    App\Processor\Game\GamePlayerCardProcessor:
        autowire: true
        tags:
            - { name: 'app.game_processor', priority: 50 }

    App\Processor\Game\PlayerReadyStateProcessor:
        autowire: true
        tags:
            - { name: 'app.game_processor', priority: 60 }

    App\Processor\Game\GameFlushProcessor:
        autowire: true
        tags:
            - { name: 'app.game_processor', priority: 70 }

    App\Processor\Game\GameUpdateProcessor:
        autowire: true
        tags:
            - { name: 'app.game_processor', priority: 100 }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
